acdc:
  path_acdc: "../../datasets/acdc"
  path_processed: "../../datasets/heart_segmentation/acdc"
emidec:
  path_emidec: "../../datasets/emidec-dataset-1.0.1"
  path_processed: "../../datasets/heart_segmentation/emidec"
